spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@mongo_db/lotto-web    # mongodb://[username:password@]host1[:port1]/[database-name]

lotto:
  time:
    drawDayOfWeek: 6
    drawHour: 12
    drawMinutes: 0
    drawSeconds: 0
#    drawTime: "${lotto.time.drawHour}:${lotto.time.drawMinutes}:${lotto.time.drawSeconds}"
  checker:
    lotteryRunOccurrence: "${lotto.time.drawSeconds} ${lotto.time.drawMinutes} ${lotto.time.drawHour} * * ${lotto.time.drawDayOfWeek}"
    lotteryResultsAnnouncement: "${lotto.time.drawSeconds} ${lotto.time.drawMinutes} ${lotto.time.drawHour} * * ${lotto.time.drawDayOfWeek}"

