spring:
  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost/lottogen?authSource=admin   # mongodb://[username:password@]host1[:port1]/[database-name]
#      uri: mongodb://admin:admin@localhost:27017/lotto-web?authSource=admin
lotto:
  checker:
    lotteryResultsAnnouncement: "*/14 * * * * *"


##    drawTime: "${lotto.time.drawHour}:${lotto.time.drawMinutes}:${lotto.time.drawSeconds}"
#  checker:
#    lotteryRunOccurrence: "${lotto.time.drawSeconds} ${lotto.time.drawMinutes} ${lotto.time.drawHour} * * ${lotto.time.drawDayOfWeek}"
#    lotteryResultsAnnouncement: "${lotto.time.drawSeconds} ${lotto.time.drawMinutes} ${lotto.time.drawHour} * * ${lotto.time.drawDayOfWeek}"
server:
  port: 8088
